version: '3.8'

services:

  dummy-mysql:
    container_name: dummy-mysql
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: dummy
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dummy-net

  dummy-back:
    container_name: dummy-back
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      dummy-mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dummy-mysql:3306/dummy?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    networks:
      - dummy-net

  nginx:
    image: nginx:latest
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - dummy-back
    networks:
      - dummy-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  dummy-net:
    driver: bridge